version: "3.8"

services:
  portfolio:
    container_name: portcontainer
    # image: node:lts-buster
    build: ./
    command: node server.js
    working_dir: /workspace/portfolio
    ports:
      - "5050:5050"
    volumes:
      - ./:/workspace/portfolio
